spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/mall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  redis:
    host: 192.168.200.10
    port: 6379
  rabbitmq:
    addresses: 192.168.200.10
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #控制台配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"

server:
  servlet:
    session:
      timeout: 120